name: getx_standard
description: A GetX Architecture by Mir Moktadir.

publish_to: 'none'


version: 2.0.0+36

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get: ^4.6.6
  logger: ^2.0.2+1
  flutter_screenutil: ^5.9.0
  dio: ^5.3.4
  http: ^1.1.2
  shared_preferences: ^2.2.2
  change_app_package_name: ^1.1.0
  iconly: ^1.0.1
  iconsax: ^0.0.8
  expandable_text: ^2.3.0
  file_picker: ^8.0.0+1
  lottie: ^3.1.0
  ionicons: ^0.2.2
  flutter_otp_text_field: ^1.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  rename_app: ^1.3.2
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  cloud_firestore: ^4.13.2
  firebase_messaging: ^14.7.5
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  graphql_flutter: ^5.1.2
  intl: ^0.19.0
  animated_text_kit: ^4.2.2
  device_info_plus: ^10.0.1
  flutter_local_notifications: ^17.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  web_socket_channel: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1
  mockito:
  build_runner:
  hive_generator:
  pub_semver:

flutter_icons:

  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon-splash/app_icon.png"

flutter_native_splash:


  background_image: "assets/images/icon-splash/splash_background.png"
  android_12:
    image: "assets/images/icon-splash/splash_icon.png"
    icon_background_color: "#ffffff"
  web: false
  fullscreen: false




flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icon-splash/
    - assets/images/onBoarding/
    - assets/vectors/
    - assets/fonts/
    - animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900