name: getx_standard
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.7.3
  flutter_native_splash: ^2.4.7
  flutter_local_notifications: ^21.0.0-dev.2
  dio: ^5.9.1
  logger: ^2.6.2
  http: ^1.6.0
  shared_preferences: ^2.5.4
  change_app_package_name: ^1.5.0
  iconly: ^1.0.1
  iconsax: ^0.0.8
  ionicons: ^0.2.2
  lottie: ^3.3.2
  cached_network_image: ^3.4.1
  remixicon: ^1.4.1
  hive_flutter: ^1.1.0
  graphql_flutter: ^5.2.1
  animated_text_kit: ^4.3.0
  pretty_dio_logger: ^1.4.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  image_cropper: ^11.0.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  device_info_plus: ^12.3.0
  pusher_channels_flutter: ^2.6.0
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  timezone: ^0.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  pub_semver: ^2.2.0



flutter_native_splash:
  background_image: "assets/images/icon-splash/splash_background.png"
  android: true
  ios: true
  web: false
  fullscreen: true
  android_12:
    image: "assets/images/icon-splash/splash_icon.png"
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icon-splash/
    - assets/images/onBoarding/
    - assets/images/loader_icon/
    - assets/vectors/
    - assets/fonts/
    - animations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900


